"""
API Schemas Package

This package contains Pydantic schemas for API request/response validation.
The schemas provide strong typing, validation, and documentation for the API layer.
"""

from .alliance import (
    AllianceSelectionRequest,
    AllianceSelectionResponse,
    AllianceState,
    LockedPicklistResponse,
    LockPicklistRequest,
    TeamActionRequest,
    TeamActionResponse,
    TeamStatus,
)
from .common import (
    ErrorResponse,
    HealthCheckResponse,
    PaginatedResponse,
    StatusResponse,
    SuccessResponse,
)
from .dataset import (
    BuildDatasetRequest,
    BuildDatasetResponse,
    DatasetExportResponse,
    DatasetField,
    DatasetFieldsResponse,
    DatasetFilterRequest,
    DatasetResponse,
    DatasetSource,
    DatasetStats,
    DatasetStatusResponse,
)
from .picklist import (
    BatchProcessingStatus,
    MetricPriority,
    PicklistGenerateRequest,
    PicklistGenerateResponse,
    PicklistUpdateRequest,
    PicklistUpdateResponse,
    RankMissingTeamsRequest,
    RankMissingTeamsResponse,
    TeamRanking,
    UserRanking,
)
from .schema import (
    FieldCategory,
    FieldMapping,
    FieldType,
    LearnSchemaRequest,
    LearnSchemaResponse,
    MapFieldsRequest,
    SchemaExportResponse,
    SchemaField,
    SchemaResponse,
    SchemaTemplate,
    SchemaTemplatesResponse,
    SchemaValidationIssue,
    UpdateSchemaRequest,
    ValidateSchemaRequest,
    ValidateSchemaResponse,
)
from .setup import (
    EventDetailResponse,
    EventInfo,
    EventsRequest,
    EventsResponse,
    EventTeam,
    SetupConfiguration,
    SetupInfoResponse,
    SetupStep,
    StartSetupRequest,
    StartSetupResponse,
    UpdateSetupRequest,
)
from .validation import (
    CorrectionRequest,
    CorrectionSuggestionsResponse,
    IgnoreMatchRequest,
    OutlierDetails,
    OutlierType,
    TodoItem,
    TodoListResponse,
    TodoStatus,
    TodoUpdateRequest,
    ValidationIssue,
    ValidationRequest,
    ValidationResponse,
    ValidationSeverity,
    VirtualScoutEntry,
    VirtualScoutRequest,
    VirtualScoutResponse,
)

__all__ = [
    # Common schemas
    "SuccessResponse",
    "ErrorResponse",
    "PaginatedResponse",
    "StatusResponse",
    "HealthCheckResponse",
    # Picklist schemas
    "MetricPriority",
    "PicklistGenerateRequest",
    "PicklistGenerateResponse",
    "PicklistUpdateRequest",
    "PicklistUpdateResponse",
    "RankMissingTeamsRequest",
    "RankMissingTeamsResponse",
    "UserRanking",
    "TeamRanking",
    "BatchProcessingStatus",
    # Alliance schemas
    "LockPicklistRequest",
    "LockedPicklistResponse",
    "AllianceSelectionRequest",
    "AllianceSelectionResponse",
    "TeamActionRequest",
    "TeamActionResponse",
    "AllianceState",
    "TeamStatus",
    # Validation schemas
    "OutlierType",
    "TodoStatus",
    "ValidationSeverity",
    "OutlierDetails",
    "ValidationIssue",
    "TodoItem",
    "VirtualScoutEntry",
    "ValidationRequest",
    "CorrectionRequest",
    "IgnoreMatchRequest",
    "VirtualScoutRequest",
    "TodoUpdateRequest",
    "ValidationResponse",
    "CorrectionSuggestionsResponse",
    "TodoListResponse",
    "VirtualScoutResponse",
    # Dataset schemas
    "DatasetSource",
    "DatasetField",
    "DatasetStats",
    "BuildDatasetRequest",
    "DatasetFilterRequest",
    "BuildDatasetResponse",
    "DatasetStatusResponse",
    "DatasetResponse",
    "DatasetExportResponse",
    "DatasetFieldsResponse",
    # Setup schemas
    "EventInfo",
    "EventTeam",
    "SetupConfiguration",
    "SetupStep",
    "EventsRequest",
    "StartSetupRequest",
    "UpdateSetupRequest",
    "EventsResponse",
    "EventDetailResponse",
    "SetupInfoResponse",
    "StartSetupResponse",
    # Schema schemas
    "FieldType",
    "FieldCategory",
    "SchemaField",
    "FieldMapping",
    "SchemaValidationIssue",
    "SchemaTemplate",
    "LearnSchemaRequest",
    "UpdateSchemaRequest",
    "MapFieldsRequest",
    "ValidateSchemaRequest",
    "LearnSchemaResponse",
    "SchemaResponse",
    "ValidateSchemaResponse",
    "SchemaTemplatesResponse",
    "SchemaExportResponse",
]
